name: ci

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.12.0

      - uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - run: npm install

      - run: npm run lint

      - run: |
          set -a
          . ./.env.example
          set +a
          npm run test

      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}

      - id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: appvia/githubUserManager/githubUserManager
          tag-sha: true
          tag-latest: true
          tag-semver: |
            {{version}}
          label-custom: |
            org.opencontainers.image.vendor=appvia
            org.opencontainers.image.documentation=https://github.com/appvia/githubUserManager
            org.opencontainers.image.authors=Chris Nesbitt-Smith <chris.nesbitt-smith@appvia.io>
            org.opencontainers.image.url=https://github.com/appvia/githubUserManager
            maintainer=appvia


      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: appvia/githubUserManager/githubUserManager
          tag_with_ref: true